theme: jekyll-theme-cayman
title: Baptiste Averly
description: Independant field ecologist and data analysttt
description_en: Independant field ecologist and data analystt
description_fr: Ecologue de terrain et analyste de données indépendant
baseurl: /
